name: Solver-Build-Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build Test (Ubuntu)
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Debug (Ubuntu)
        run: |
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake ..
          make
          ctest

  ci_integrational:
    name: Integrational tests
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt

      - name: Build Release (Ubuntu)
        run: |
          mkdir cmake-build-release
          cd cmake-build-release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          python3 ../tests/SATLIB/test_runner.py ./CDCL_solver.exe -c
