name: Solver-Build-Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Build Test (Ubuntu)
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Debug (Ubuntu)
        run: |
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake ..
          make
          ctest
